// Game Settings
export const DEFAULT_TIME_PER_TURN = 20;
export const DEFAULT_ROUNDS = 5;

// Avatar Options
export const AVATAR_OPTIONS = [
  "👦",
  "👧",
  "👨",
  "👩",
  "🧑",
  "👶",
  "🧒",
  "🧓",
  "👴",
  "👵",
  "👸",
  "🤴",
  "👼",
  "🦸‍♂️",
  "🦸‍♀️",
  "🧙‍♂️",
  "🧙‍♀️",
  "🧚‍♂️",
  "🧚‍♀️",
  "🦊",
  "🐶",
  "🐱",
  "🐼",
  "🐨",
  "🐯",
  "🦁",
  "🐮",
  "🐷",
  "🐸",
  "🐙",
];

// Game Colors
export const GAME_COLORS = {
  animals: {
    from: "green-400",
    via: "teal-500",
    to: "blue-600",
    overlayFrom: "emerald-400",
    overlayVia: "green-500",
    overlayTo: "teal-500",
  },
  colors: {
    from: "pink-400",
    via: "purple-500",
    to: "indigo-600",
    overlayFrom: "rose-400",
    overlayVia: "pink-500",
    overlayTo: "purple-500",
  },
  digitalLiteracy: {
    from: "cyan-400",
    via: "blue-500",
    to: "indigo-600",
    overlayFrom: "teal-400",
    overlayVia: "cyan-500",
    overlayTo: "blue-500",
  },
  drawing: {
    from: "indigo-400",
    via: "blue-500",
    to: "cyan-400",
    overlayFrom: "blue-400",
    overlayVia: "indigo-500",
    overlayTo: "cyan-500",
  },
  geography: {
    from: "blue-400",
    via: "cyan-500",
    to: "teal-600",
    overlayFrom: "sky-400",
    overlayVia: "blue-500",
    overlayTo: "cyan-500",
  },
  math: {
    from: "orange-400",
    via: "amber-500",
    to: "yellow-600",
    overlayFrom: "red-400",
    overlayVia: "orange-500",
    overlayTo: "amber-500",
  },
  memory: {
    from: "cyan-400",
    via: "teal-500",
    to: "emerald-600",
    overlayFrom: "sky-400",
    overlayVia: "cyan-500",
    overlayTo: "teal-500",
  },
  quiz: {
    from: "violet-400",
    via: "purple-500",
    to: "fuchsia-600",
    overlayFrom: "indigo-400",
    overlayVia: "violet-500",
    overlayTo: "purple-500",
  },
  science: {
    from: "emerald-400",
    via: "green-500",
    to: "lime-600",
    overlayFrom: "teal-400",
    overlayVia: "emerald-500",
    overlayTo: "green-500",
  },
};
